import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Repository Standards — RepoRules.dev",
  description:
    "Structured repository conventions designed to keep AI-generated code predictable and maintainable over time.",
};

const RULE_CARD =
  "rounded-xl border border-[#2a2d35] bg-[#16181d] p-6 mb-6";
const SIDEBAR_ITEM =
  "block text-sm text-zinc-400 transition-colors hover:text-zinc-100";
const SECTION_TITLE = "text-2xl font-semibold tracking-tight text-zinc-100 mb-6";

const RULES = [
  {
    id: "server-components",
    label: "Server Components",
    rules: [
      {
        title: "Server Components First",
        badge: "Architecture",
        desc: "Always prefer server components unless interactivity is required.",
        why: "Reduces client-side complexity and avoids unnecessary hydration.",
        bad: "Fetching data inside client components.",
        good: "Fetch data in server components and pass serialized props.",
        failure: "Duplicated fetching logic across pages.",
      },
    ],
  },
  {
    id: "architecture",
    label: "Architecture",
    rules: [
      {
        title: "Feature-Based Structure",
        badge: "Architecture",
        desc: "Group files by feature instead of file type.",
        why: "Keeps features self-contained. Prevents AI from creating scattered utilities.",
        bad: "Flat file structure with no domain boundaries.",
        good: "/features/auth, /features/billing, /features/dashboard",
        failure: "Mixed concerns and duplicated logic across features.",
      },
      {
        title: "Shared UI Primitives",
        badge: "Architecture",
        desc: "Avoid duplicated UI patterns. Keep reusable UI in /components/ui.",
        why: "AI tools generate inconsistent UI without shared primitives.",
        bad: "Inline styles and duplicated button patterns across features.",
        good: "<Button />, <Input />, <Dialog /> reused from /components/ui",
        failure: "Inconsistent UI generated by different AI prompts.",
      },
      {
        title: "Isolated Business Logic",
        badge: "Architecture",
        desc: "Never mix UI rendering with domain logic.",
        why: "Keeps AI-generated code testable and refactorable.",
        bad: "API calls and state management inside component files.",
        good: "Logic in /features/*/actions or /features/*/hooks",
        failure: "Server actions mixed with UI rendering code.",
      },
    ],
  },
  {
    id: "naming",
    label: "Naming",
    rules: [
      {
        title: "Naming Conventions",
        badge: "Naming",
        desc: "Use explicit names. Avoid generic file names.",
        why: "Generic names cause AI tools to create duplicated utilities.",
        bad: "helpers.ts, utils.ts, common.ts",
        good: "auth-validator.ts, billing-service.ts, dashboard-query.ts",
        failure: "Duplicated utility files with overlapping logic.",
      },
    ],
  },
  {
    id: "pr-workflow",
    label: "PR Workflow",
    rules: [
      {
        title: "PR Constraints",
        badge: "PR Workflow",
        desc: "Keep PRs under 300 LOC. Avoid mixed concerns.",
        why: "Large PRs hide AI-generated inconsistencies and duplicated patterns.",
        bad: "500+ line PRs with multiple unrelated changes.",
        good: "Focused PRs under 300 LOC with clear scope.",
        failure: "Inconsistent architecture hidden in oversized PRs.",
      },
    ],
  },
  {
    id: "testing",
    label: "Testing",
    rules: [
      {
        title: "Testing Standards",
        badge: "Testing",
        desc: "Test critical flows. Prefer integration tests.",
        why: "AI-generated code often misses edge cases and error states.",
        bad: "Snapshot-heavy tests that hide regressions.",
        good: "Behavior-based tests covering loading, error, and empty states.",
        failure: "Tests passing but production flows broken.",
      },
    ],
  },
  {
    id: "performance",
    label: "Performance",
    rules: [
      {
        title: "Performance Standards",
        badge: "Performance",
        desc: "Lazy load heavy charts. Avoid client waterfalls.",
        why: "AI tools don't consider bundle size unless constrained.",
        bad: "All components eagerly loaded on the client.",
        good: "Server components with streaming and lazy-loaded heavy UI.",
        failure: "Unnecessary client bundles slowing down page loads.",
      },
    ],
  },
  {
    id: "ai-constraints",
    label: "AI Constraints",
    rules: [
      {
        title: "AI Output Constraints",
        badge: "AI Constraints",
        desc: "Preserve existing architecture. Avoid introducing new folder structures.",
        why: "AI tools generate alternative patterns unless strictly constrained.",
        bad: "AI creating new folder structures outside feature boundaries.",
        good: "AI following existing feature-based architecture patterns.",
        failure: "Inconsistent repo structure from unconstrained AI output.",
      },
    ],
  },
  {
    id: "migration",
    label: "Migration",
    rules: [
      {
        title: "Migration Constraints",
        badge: "Migration",
        desc: "Old patterns still exist. Prevent AI from adding to legacy code.",
        why: "AI tools can't distinguish between current and deprecated patterns.",
        bad: "AI adding new features using deprecated hook patterns.",
        good: "AI following migration guide and using current standards.",
        failure: "Legacy patterns duplicated across new features.",
      },
    ],
  },
];

export default function RulesPage() {
  return (
    <div className="mx-auto max-w-7xl px-6 py-20">
      {/* Tag */}
      <span className="inline-flex items-center rounded-full border border-zinc-700 bg-zinc-900 px-3 py-1 font-mono text-xs text-zinc-300">
        Repository Standards
      </span>

      {/* H1 */}
      <h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-tight tracking-tight text-zinc-100">
        AI repository standards
        <br />
        for long-term maintainability
      </h1>

      {/* Subtitle */}
      <p className="mt-6 max-w-3xl text-lg leading-8 text-zinc-300">
        Structured repository conventions designed to keep AI-generated code
        predictable and maintainable over time.
      </p>

      {/* Repo stats */}
      <div className="mt-8 flex gap-5 font-mono text-xs text-zinc-500">
        <span>57 rules</span>
        <span>12 categories</span>
        <span>Updated 2 days ago</span>
      </div>

      {/* Search */}
      <input
        type="text"
        placeholder="Search repository rules..."
        className="mt-10 w-full max-w-xl rounded-xl border border-[#2a2d35] bg-[#16181d] px-4 py-3 text-sm text-zinc-300 outline-none"
      />

      {/* Filters */}
      <div className="mt-6 flex flex-wrap gap-3">
        <span className="rounded-md bg-zinc-100 px-3 py-1.5 font-mono text-xs text-zinc-900">
          All
        </span>
        {[
          "Architecture",
          "Naming",
          "Testing",
          "PR Workflow",
          "Performance",
          "Security",
        ].map((f) => (
          <span
            key={f}
            className="rounded-md border border-zinc-700 px-3 py-1.5 font-mono text-xs text-zinc-400 hover:text-zinc-100"
          >
            {f}
          </span>
        ))}
      </div>

      {/* Layout */}
      <div className="mt-16 grid grid-cols-1 gap-10 lg:grid-cols-[260px_1fr]">
        {/* Sidebar */}
        <aside className="hidden lg:block">
          <nav className="sticky top-24 space-y-2">
            <p className="mb-4 text-xs font-medium uppercase tracking-wider text-zinc-500">
              Rule Categories
            </p>
            {RULES.map((s) => (
              <a key={s.id} href={`#${s.id}`} className={SIDEBAR_ITEM}>
                {s.label}
              </a>
            ))}
          </nav>
        </aside>

        {/* Content */}
        <div className="min-w-0">
          {RULES.map((section) => (
            <section key={section.id} id={section.id} className="mb-14">
              {section.rules.map((rule) => (
                <div key={rule.title} className={RULE_CARD}>
                  <div className="mb-3 flex items-center gap-3">
                    <span className="rounded-md border border-zinc-700 bg-zinc-950 px-2 py-0.5 font-mono text-[10px] text-zinc-500">
                      {rule.badge}
                    </span>
                  </div>
                  <h3 className="text-lg font-semibold text-zinc-100">
                    {rule.title}
                  </h3>
                  <p className="mt-3 font-mono text-sm leading-relaxed text-zinc-400">
                    {rule.desc}
                  </p>
                  <div className="mt-4">
                    <span className="font-mono text-xs text-zinc-500">
                      Why:
                    </span>
                    <p className="mt-1 font-mono text-sm text-zinc-400">
                      {rule.why}
                    </p>
                  </div>
                  <div className="mt-4 grid gap-4 sm:grid-cols-2">
                    <div className="rounded-lg border border-red-900/40 bg-red-950/20 p-3">
                      <span className="font-mono text-xs text-red-400">
                        Bad Example
                      </span>
                      <p className="mt-1 font-mono text-sm text-zinc-400">
                        {rule.bad}
                      </p>
                    </div>
                    <div className="rounded-lg border border-green-900/40 bg-green-950/20 p-3">
                      <span className="font-mono text-xs text-green-400">
                        Good Example
                      </span>
                      <p className="mt-1 font-mono text-sm text-zinc-400">
                        {rule.good}
                      </p>
                    </div>
                  </div>
                  <div className="mt-4">
                    <span className="font-mono text-xs text-amber-500">
                      Common Failure
                    </span>
                    <p className="mt-1 font-mono text-sm text-zinc-400">
                      {rule.failure}
                    </p>
                  </div>
                </div>
              ))}
            </section>
          ))}

          {/* Common Failures */}
          <section className="mt-14">
            <h2 className={SECTION_TITLE}>
              Common AI Repository Failures
            </h2>
            <div className="rounded-xl border border-zinc-800 bg-[#16181d] p-6 font-mono text-sm leading-7 text-zinc-400">
              {[
                "duplicated hooks",
                "inconsistent naming",
                "repeated validation schemas",
                "oversized utility files",
                "mixed client/server logic",
                "unstable repo conventions",
              ].map((f) => (
                <div key={f}>- {f}</div>
              ))}
            </div>
          </section>

          {/* Migration Notes */}
          <section className="mt-14">
            <h2 className={SECTION_TITLE}>Migration Notes</h2>
            <div className="rounded-xl border border-zinc-800 bg-[#16181d] p-6 font-mono text-sm leading-7 text-zinc-400">
              {[
                "old auth hooks still exist",
                "validation migration in progress",
                "dashboard architecture under refactor",
              ].map((n) => (
                <div key={n} className="flex items-start gap-2">
                  <span className="mt-1 text-amber-400">*</span>
                  <span>{n}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Recent Changes */}
          <section className="mt-14">
            <h2 className={SECTION_TITLE}>Recent Rule Updates</h2>
            <div className="max-w-xl rounded-xl border border-[#2a2d35] bg-[#151922] p-5 font-mono text-sm text-zinc-400">
              <div className="mb-4 text-xs text-zinc-500">// changelog</div>
              <div className="space-y-4">
                <div>
                  <div className="text-xs text-blue-300">v0.4.2</div>
                  <div className="mt-1 space-y-1">
                    <div>- updated PR constraints</div>
                    <div>- improved validation standards</div>
                  </div>
                </div>
                <div>
                  <div className="text-xs text-blue-300">v0.4.1</div>
                  <div className="mt-1 space-y-1">
                    <div>- added AI output constraints</div>
                  </div>
                </div>
                <div>
                  <div className="text-xs text-blue-300">v0.4.0</div>
                  <div className="mt-1 space-y-1">
                    <div>- introduced architecture rules</div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
