"use client";

import { useState } from "react";
import Link from "next/link";
import { Search } from "lucide-react";

const RULES = [
  {
    id: "server-components",
    label: "Server Components",
    badge: "Architecture",
    title: "Server Components First",
    desc: "Always prefer server components unless interactivity is required.",
    context: "Used inside: billing workflow, dashboard modules, shared validators",
    legacy: "Old dashboard hooks still depend on legacy validation patterns.",
    migration: "Partially migrated.",
    why: "Reduces client-side complexity and avoids unnecessary hydration.",
    bad: "Fetching data inside client components.",
    good: "Fetch data in server components and pass serialized props.",
    failure: "Duplicated fetching logic across pages.",
  },
  {
    id: "architecture",
    label: "Architecture",
    badge: "Architecture",
    title: "Feature-Based Structure",
    desc: "Group files by feature instead of file type.",
    context: "Used inside: billing workflow, dashboard modules",
    legacy: "Old dashboard modules still use flat structure.",
    migration: "Partially migrated.",
    why: "Keeps features self-contained. Prevents AI from creating scattered utilities.",
    bad: "Flat file structure with no domain boundaries.",
    good: "/features/auth, /features/billing, /features/dashboard",
    failure: "Mixed concerns and duplicated logic across features.",
  },
  {
    id: "shared-ui",
    badge: "Architecture",
    title: "Shared UI Primitives",
    desc: "Avoid duplicated UI patterns. Keep reusable UI in /components/ui.",
    context: "Used inside: all dashboard modules",
    legacy: "Analytics module still uses inline styles.",
    migration: "Migration in progress.",
    why: "AI tools generate inconsistent UI without shared primitives.",
    bad: "Inline styles and duplicated button patterns across features.",
    good: "Button, Input, Dialog reused from /components/ui",
    failure: "Inconsistent UI generated by different AI prompts.",
  },
  {
    id: "business-logic",
    badge: "Architecture",
    title: "Isolated Business Logic",
    desc: "Never mix UI rendering with domain logic.",
    context: "Used inside: billing service, auth module",
    legacy: "Dashboard components still contain inline queries.",
    migration: "Pending.",
    why: "Keeps AI-generated code testable and refactorable.",
    bad: "API calls and state management inside component files.",
    good: "Logic in /features/*/actions or /features/*/hooks",
    failure: "Server actions mixed with UI rendering code.",
  },
  {
    id: "naming",
    badge: "Naming",
    title: "Naming Conventions",
    desc: "Use explicit names. Avoid generic file names.",
    context: "Used inside: all feature modules",
    legacy: "Legacy utils/ folder still contains mixed helpers.",
    migration: "Partially migrated.",
    why: "Generic names cause AI tools to create duplicated utilities.",
    bad: "helpers.ts, utils.ts, common.ts",
    good: "auth-validator.ts, billing-service.ts, dashboard-query.ts",
    failure: "Duplicated utility files with overlapping logic.",
  },
  {
    id: "pr-workflow",
    badge: "PR Workflow",
    title: "PR Constraints",
    desc: "Keep PRs under 300 LOC. Avoid mixed concerns.",
    context: "Used inside: all workflow repositories",
    legacy: "Billing migration PRs still exceed 400 LOC.",
    migration: "Enforcing new limits.",
    why: "Large PRs hide AI-generated inconsistencies and duplicated patterns.",
    bad: "500+ line PRs with multiple unrelated changes.",
    good: "Focused PRs under 300 LOC with clear scope.",
    failure: "Inconsistent architecture hidden in oversized PRs.",
  },
  {
    id: "testing",
    badge: "Testing",
    title: "Testing Standards",
    desc: "Test critical flows. Prefer integration tests.",
    context: "Used inside: billing, auth, dashboard",
    legacy: "Old test files still use snapshot approach.",
    migration: "Migration in progress.",
    why: "AI-generated code often misses edge cases and error states.",
    bad: "Snapshot-heavy tests that hide regressions.",
    good: "Behavior-based tests covering loading, error, and empty states.",
    failure: "Tests passing but production flows broken.",
  },
  {
    id: "performance",
    badge: "Performance",
    title: "Performance Standards",
    desc: "Lazy load heavy charts. Avoid client waterfalls.",
    context: "Used inside: dashboard, analytics",
    legacy: "Analytics page still eagerly loads charts.",
    migration: "Pending.",
    why: "AI tools don't consider bundle size unless constrained.",
    bad: "All components eagerly loaded on the client.",
    good: "Server components with streaming and lazy-loaded heavy UI.",
    failure: "Unnecessary client bundles slowing down page loads.",
  },
  {
    id: "ai-constraints",
    badge: "AI Constraints",
    title: "AI Output Constraints",
    desc: "Preserve existing architecture. Avoid introducing new folder structures.",
    context: "Used inside: all AI-generated code paths",
    legacy: "No legacy exceptions — all new code must follow constraints.",
    migration: "Fully active.",
    why: "AI tools generate alternative patterns unless strictly constrained.",
    bad: "AI creating new folder structures outside feature boundaries.",
    good: "AI following existing feature-based architecture patterns.",
    failure: "Inconsistent repo structure from unconstrained AI output.",
  },
  {
    id: "migration",
    badge: "Migration",
    title: "Migration Constraints",
    desc: "Old patterns still exist. Prevent AI from adding to legacy code.",
    context: "Used inside: billing hooks, dashboard queries",
    legacy: "Auth hooks still use deprecated patterns.",
    migration: "Migration planned Q3 2026.",
    why: "AI tools can't distinguish between current and deprecated patterns.",
    bad: "AI adding new features using deprecated hook patterns.",
    good: "AI following migration guide and using current standards.",
    failure: "Legacy patterns duplicated across new features.",
  },
];

const categories = [
  "All",
  "Architecture",
  "Naming",
  "Testing",
  "PR Workflow",
  "Performance",
  "Security",
];

export default function RulesPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");

  const filtered = RULES.filter((rule) => {
    const q = searchQuery.toLowerCase();
    const matchesSearch =
      rule.title.toLowerCase().includes(q) ||
      rule.desc.toLowerCase().includes(q) ||
      rule.badge.toLowerCase().includes(q);
    const matchesCategory =
      activeCategory === "All" || rule.badge === activeCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <main className="min-h-screen bg-[#0d0f14] text-zinc-100">
      <div className="mx-auto max-w-7xl px-6 py-16">
        {/* Hero */}
        <div>
          <div className="inline-flex items-center rounded-full border border-zinc-700 bg-zinc-900 px-3 py-1 font-mono text-xs text-zinc-300">
            Repository Standards
          </div>
          <h1 className="mt-4 max-w-4xl text-5xl font-semibold leading-tight tracking-tight">
            AI repository standards
            <br />
            for long-term maintainability
          </h1>
          <p className="mt-4 max-w-3xl text-lg leading-8 text-zinc-300">
            Structured repository conventions designed to keep AI-generated code
            predictable and maintainable over time.
          </p>
          <div className="mt-5 flex gap-5 font-mono text-xs text-zinc-500">
            <span>57 rules</span>
            <span>12 categories</span>
            <span>Updated 2 days ago</span>
          </div>
        </div>

        {/* Search */}
        <div className="mt-8 max-w-xl">
          <div className="flex h-11 items-center gap-3 rounded-lg border border-[#2a2d35] bg-[#111318] px-4">
            <Search className="h-4 w-4 text-zinc-500" />
            <input
              type="text"
              placeholder="Search rules, constraints, workflows..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-transparent text-sm text-zinc-300 outline-none placeholder:text-zinc-500"
            />
          </div>
        </div>

        {/* Filter Tabs */}
        <div className="mt-6 flex flex-wrap gap-3">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`h-8 rounded-lg px-3 text-xs font-mono transition-colors ${
                activeCategory === cat
                  ? "border border-zinc-700 bg-[#1d2129] text-zinc-100"
                  : "border border-zinc-800 text-zinc-500 hover:border-zinc-600 hover:text-zinc-200"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Layout */}
        <div className="mt-16 grid grid-cols-1 gap-12 lg:grid-cols-[240px_1fr]">
          {/* Sidebar */}
          <aside className="hidden w-[240px] border-r border-[#22252d] pr-6 lg:block">
            <div className="sticky top-24">
              <h3 className="mb-5 text-sm font-medium">Rule Categories</h3>
              <div className="space-y-1">
                {categories.map((cat) => (
                  <button
                    key={cat}
                    onClick={() => setActiveCategory(cat)}
                    className={`block w-full text-left text-sm transition-colors ${
                      activeCategory === cat
                        ? "border-l border-zinc-100 pl-3 text-zinc-100"
                        : "pl-4 text-zinc-500 hover:text-zinc-200"
                    }`}
                  >
                    {cat}
                  </button>
                ))}
              </div>
            </div>
          </aside>

          {/* Content */}
          <div className="space-y-6">
            {filtered.map((rule) => (
              <div
                key={rule.id}
                className="rounded-xl border border-[#2a2d35] bg-[#16181d] p-6 transition-colors hover:border-zinc-600"
              >
                <div className="mb-4 font-mono text-xs text-zinc-500">
                  Maintained by RepoRules · Last updated 2 days ago
                </div>
                <div className="mb-3">
                  <span className="rounded-md border border-zinc-700 bg-zinc-950 px-2 py-0.5 font-mono text-[10px] text-zinc-500">
                    {rule.badge}
                  </span>
                </div>
                <h2 className="mb-5 text-xl font-semibold tracking-tight">
                  {rule.title}
                </h2>
                <div className="space-y-6">
                  <div>
                    <div className="mb-2 font-mono text-xs uppercase tracking-wide text-zinc-500">
                      Description
                    </div>
                    <p className="text-sm leading-7 text-zinc-300">
                      {rule.desc}
                    </p>
                  </div>
                  <div>
                    <div className="mb-2 font-mono text-xs uppercase tracking-wide text-zinc-500">
                      Why
                    </div>
                    <p className="text-sm leading-7 text-zinc-300">
                      {rule.why}
                    </p>
                  </div>
                  <div className="grid gap-6 sm:grid-cols-2">
                    <div>
                      <div className="mb-2 font-mono text-xs uppercase tracking-wide text-red-400">
                        Bad Example
                      </div>
                      <p className="text-sm leading-7 text-zinc-300">
                        {rule.bad}
                      </p>
                    </div>
                    <div>
                      <div className="mb-2 font-mono text-xs uppercase tracking-wide text-green-400">
                        Good Example
                      </div>
                      <p className="text-sm leading-7 text-zinc-300">
                        {rule.good}
                      </p>
                    </div>
                  </div>
                  <div>
                    <div className="mb-2 font-mono text-xs uppercase tracking-wide text-amber-400">
                      Common Failure
                    </div>
                    <p className="text-sm leading-7 text-zinc-300">
                      {rule.failure}
                    </p>
                  </div>
                  <div>
                    <div className="mb-2 font-mono text-xs uppercase tracking-wide text-zinc-500">
                      Repository Context
                    </div>
                    <p className="text-sm leading-7 text-zinc-300">
                      {rule.context}
                    </p>
                  </div>
                  <div>
                    <div className="mb-2 font-mono text-xs uppercase tracking-wide text-zinc-500">
                      Legacy Notes
                    </div>
                    <p className="text-sm leading-7 text-zinc-500">
                      {rule.legacy}
                    </p>
                  </div>
                  <div>
                    <div className="mb-2 font-mono text-xs uppercase tracking-wide text-zinc-500">
                      Migration Status
                    </div>
                    <p className="text-sm leading-7 text-zinc-300">
                      {rule.migration}
                    </p>
                  </div>
                </div>
              </div>
            ))}

            {/* Repository Files */}
            <div className="mt-12 rounded-xl border border-[#2a2d35] bg-[#151922] p-5">
              <div className="mb-4 text-sm font-medium">Repository Files</div>
              <div className="font-mono text-xs leading-7">
                <Link href="/repository/rules" className="text-zinc-500 hover:text-zinc-200 transition-colors">rules.md</Link><br />
                <Link href="/repository/memory" className="text-zinc-500 hover:text-zinc-200 transition-colors">memory.md</Link><br />
                <span className="text-zinc-600">architecture.md</span><br />
                <Link href="/repository/migration-notes" className="text-zinc-500 hover:text-zinc-200 transition-colors">migration-notes.md</Link><br />
                <span className="text-zinc-600">testing-guidelines.md</span><br />
                <span className="text-zinc-600">pnpm-workspace.yaml</span><br />
                <span className="text-zinc-600">turbo.json</span>
              </div>
            </div>

            {/* Recent Repository Incidents */}
            <div className="mt-12 rounded-xl border border-[#2a2d35] bg-[#151922] p-6">
              <div className="mb-4 text-sm font-medium">
                Recent Repository Incidents
              </div>
              <div className="font-mono text-sm leading-7 text-zinc-400">
                2026-05-08
                <br />
                - duplicated auth hooks introduced during billing refactor
                <br />
                <br />
                2026-05-04
                <br />
                - dashboard migration broke validation consistency
                <br />
                <br />
                2026-04-28
                <br />
                - old analytics modules bypassed server boundaries
              </div>
            </div>

            {/* Engineering Constraints */}
            <div className="mt-12 rounded-xl border border-[#2a2d35] bg-[#16181d] p-6">
              <div className="mb-4 text-sm font-medium">
                Engineering Constraints
              </div>
              <div className="font-mono text-sm leading-7 text-zinc-400">
                - avoid large rewrites
                <br />
                - preserve migration consistency
                <br />
                - maintain repo predictability
                <br />
                - reduce architectural drift
                <br />
                - avoid duplicated business logic
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
